/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0ca6bb44-8971-45a9-9b76-2806d3fab7df",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_m4W6re4bs",
    "aws_user_pools_web_client_id": "6cuaqan2sodjf428akmaiivqfp",
    "oauth": {},
    "aws_mobile_analytics_app_id": "93a9e753321d468fb44ecf097c248097",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_content_delivery_bucket": "pico-20210317225137-hostingbucket-picoenv",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://pico-20210317225137-hostingbucket-picoenv.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
